name: Java Maven Pipeline

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Increase Jar version
        run: |
          echo "Bumping Jar version..."
          jar_version=$(cat VERSION)
          new_jar_version=${jar_version%.*}.$((jar_version##*.))
          echo "New Jar version: $new_jar_version"
          echo $new_jar_version > VERSION
      
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add pom.xml
          git commit -m "Bump version"
      
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
      
              
      - name: Compile code
        working-directory: ./myapp
        run: mvn compile
        
      - name: Package artifact
        working-directory: ./myapp
        run: mvn package
        
      - name: Create artifact item
        uses: actions/upload-artifact@v2
        with:
          name: my-app
          path: target/my-app.jar
