name: Java Maven Pipeline

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Increase version
        uses: chrisgahlert/maven-version@v1
        with:
          version-type: 'increment'
          version-segment: 'patch'
          update-pom: 'true'
              
      - name: Compile code
        working-directory: ./myapp
        run: mvn compile
        
      - name: Package artifact
        working-directory: ./myapp
        run: mvn package
        
      - name: Create artifact item
        uses: actions/upload-artifact@v2
        with:
          name: my-app
          path: target/my-app.jar
