name: Java Maven Pipeline

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Parse XML File
        uses: actions/xml-parser@v1
        id: xml
        with:
          path: /home/runner/work/maven-hello-world/maven-hello-world/myapp/pom.xml
          xpath: /project/version
      
      - name: Print XML Data
        run: echo "${{ steps.xml.outputs.result }}"
              
      - name: Compile code
        working-directory: ./myapp
        run: mvn compile
        
      - name: Package artifact
        working-directory: ./myapp
        run: mvn package
        
      - name: Create artifact item
        uses: actions/upload-artifact@v2
        with:
          name: my-app
          path: target/my-app.jar
