name: Java Maven Pipeline

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: secrets
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Increase patch version
        id: version
        working-directory: ./myapp
        run:  |
          old_version=$(mvn help:evaluate -Dexpression="project.version" -q -DforceStdout)
          echo "OLD_VERSION=$old_version" >> $GITHUB_ENV
          major=$(echo $old_version | cut -d '.' -f 1)
          minor=$(echo $old_version | cut -d '.' -f 2)
          patch=$(echo $old_version | cut -d '.' -f 3)
          patch=$((patch + 1))
          new_version="${major}.${minor}.${patch}"
          echo "NEW_VERSION=$new_version" >> $GITHUB_ENV
          mvn versions:set -DnewVersion=$new_version
      
      - name: Commit and push the new version
        uses: Smart-Transportation/push@v1.3
        with:
          github_token: ${{ secrets.TOKEN }}
          message: Increase patch version
          directory: ./myapp
        
      - name: Compile code
        working-directory: ./myapp
        run: mvn compile
        
      - name: Package artifact
        working-directory: ./myapp
        run: mvn package
        
      - name: Create artifact item
        uses: actions/upload-artifact@v2
        with:
          name: myapp-1.0.0.jar
          path: ./myapp/target/myapp-1.0.0.jar
          
      - name: Login to Docker Hub
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        
      - name: Build and push Docker image
        uses: docker/build-push-action@v4.0.0
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ DOCKER_REPO_NAME }}:$NEW_VERSION
