name: Java Maven Pipeline

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Increase version
        run: |
          VERSION=$(grep -oP '(?<=<version>)[^<]+' pom.xml)
          PATCH=$(echo $VERSION | awk -F '.' '{print $3}')
          NEW_VERSION=$(echo $VERSION | sed "s/$PATCH/$((PATCH+1))/")
          echo $NEW_VERSION > version.txt
          mvn versions:set -DnewVersion=$NEW_VERSION
              
      - name: Compile code
        working-directory: ./myapp
        run: mvn compile
        
      - name: Package artifact
        working-directory: ./myapp
        run: mvn package
        
      - name: Create artifact item
        uses: actions/upload-artifact@v2
        with:
          name: my-app
          path: target/my-app.jar
